[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_pdas = "GrEsoJCRNoSwRPAQe5qB3keYXN7tKouCQ9bFkWbKeQqb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/revazmeishvili/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
